# This is a TOML configuration file.

# Connection details of a Electrum Server.
[electrum]
  ServerHost  = "tbtc-electrumx-server.tbtc.svc.cluster.local"
  ServerPort  = "50002"
  Protocol    = "SSL" # TCP or SSL

# TLS configuration for a SSL connection to a Electrum Server.
[electrum.TLSConfig]
  # Skip server certificates verification - a temporary solution for development.
  InsecureSkipVerify = true

# Connection details for Block Cypher API.
[blockcypher]
  Token   = "d195ca15455f42b7842abd7c691191c9"
  Coin    = "btc"
  Chain   = "test3"

# Connection details of ethereum blockchain.
[ethereum]
  URL                 = "Set by Kube"
  PrivateKey          = "Set by Kube"

# Addresses of contracts deployed on ethereum blockchain.
[ethereum.ContractAddresses]
  TBTCSystem = "Set by Kube"
