version: 2.1
executors:
  docker-node:
    docker:
      - image: circleci/node:11
jobs:
  test_solidity:
    executor: docker-node
    steps:
        - checkout
        - run: sudo npm install -g ganache-cli@6.4.2
        - run:
            name: Running testrpc
            command: ganache-cli
            background: true
        - run: cd implementation/contracts && npm install && npm run test
  generate_pngs:
    docker:
      - image: keepnetwork/texlive:15
    steps:
      - checkout
      - run:
          name: Generate TeX-based PNGs
          command: |
            mkdir -p /tmp/docs/img
            make pngs
            cp -r img/generated /tmp/docs/img/generated
      - persist_to_workspace:
          root: /tmp/docs
          paths:
            - img/generated/*.png
  generate_docs_tex:
    docker:
      - image: keepnetwork/texlive:15
    steps:
      - checkout
      - run:
          name: Generate TeX Document Files
          command: |
            mkdir -p /tmp/docs
            make build.pdf
            cp *.pdf /tmp/docs
      - persist_to_workspace:
          root: /tmp/docs
          paths:
            - ./*.pdf
  generate_docs_asciidoctor:
    docker:
      - image: asciidoctor/docker-asciidoctor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Generate Asciidoctor PDF/HTML Files
          command: |
            set -ex
            shopt -s extglob globstar nullglob
            asciidoctor -a revdate=`date +%Y-%m-%d` --failure-level=ERROR *.adoc **/*.adoc
            for a in $(ls *.html **/*.html); do set +x; mkdir -p /tmp/docs/$(dirname $a); cp $a /tmp/docs/$(dirname $a)/; done
            set -x
            asciidoctor-pdf -a revdate=`date +%Y-%m-%d` *.adoc **/*.adoc
            for a in $(ls *.pdf **/*.pdf); do set +x; mkdir -p /tmp/docs/$(dirname $a); cp $a /tmp/docs/$(dirname $a)/; done
      - persist_to_workspace:
          root: /tmp/docs
          paths:
            - ./
  upload_docs:
    docker:
      - image: google/cloud-sdk:slim
    steps:
      - attach_workspace:
          at: /tmp/docs
      - store_artifacts:
          path: /tmp/docs
          destination: .

workflows:
  version: 2
  solidity:
    jobs:
      - test_solidity
  docs:
    jobs:
      - generate_pngs
      - generate_docs_tex
      - generate_docs_asciidoctor:
          requires:
            - generate_pngs
      - upload_docs:
          requires:
            - generate_docs_tex
            - generate_docs_asciidoctor
